language: node_js
node_js:
  - 8.12.0
install:
  - node --version
  - npm --version
  - npm install
os:
  - linux
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE spotshare;' -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
  - npm install -g knex
  - knex migrate:latest --env testing
